apiVersion: v1
kind: Namespace
metadata:
  name: nauto-console
  labels:
    name: nauto-console
    environment: production
    app.kubernetes.io/name: nauto-console
    app.kubernetes.io/version: "1.0.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nauto-console-quota
  namespace: nauto-console
spec:
  hard:
    # Compute resources
    requests.cpu: "50"      # 50 CPU cores total
    requests.memory: 100Gi   # 100GB RAM total
    limits.cpu: "100"       # 100 CPU cores limit
    limits.memory: 200Gi     # 200GB RAM limit
    
    # Storage
    requests.storage: 1Ti    # 1TB storage
    
    # Object counts
    pods: "200"             # Max 200 pods
    services: "20"          # Max 20 services
    persistentvolumeclaims: "20"
    secrets: "50"
    configmaps: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: nauto-console-limits
  namespace: nauto-console
spec:
  limits:
  - default:
      cpu: "2"          # Default 2 CPU cores
      memory: "4Gi"     # Default 4GB RAM
    defaultRequest:
      cpu: "500m"       # Default 0.5 CPU cores request
      memory: "1Gi"     # Default 1GB RAM request
    type: Container
  - default:
      cpu: "8"          # Pod default 8 CPU cores
      memory: "16Gi"    # Pod default 16GB RAM
    defaultRequest:
      cpu: "1"          # Pod default 1 CPU core request
      memory: "2Gi"     # Pod default 2GB RAM request
    type: Pod