export enum UserActivityType {
  AUTHENTICATION = 'AUTHENTICATION',
  PROFILE_MANAGEMENT = 'PROFILE_MANAGEMENT',
  ROLE_MANAGEMENT = 'ROLE_MANAGEMENT',
  SECURITY_SETTINGS = 'SECURITY_SETTINGS',
  COMPANY_ASSIGNMENT = 'COMPANY_ASSIGNMENT',
  ACCOUNT_MANAGEMENT = 'ACCOUNT_MANAGEMENT',
}
